#I "../.nuget/Microsoft.Azure.WebJobs.2.0.0/lib/net45"
#I "../.nuget/Microsoft.Azure.WebJobs.Core.2.0.0/lib/net45"
#I "../.nuget/Microsoft.Azure.WebJobs.Extensions.2.0.0/lib/net45"
#I "../.nuget/Newtonsoft.Json.10.0.2/lib/net45"
#I "../.nuget/System.Web.Http.4.0.0"
#I "../.nuget/System.Net.Http.Formatting.Extension.5.2.3.0/lib"

#r "mscorlib"
#r "System.Net.Http"
#r "System"
#r "System.Core"
#r "System.Xml"
#r "Microsoft.Azure.WebJobs"
#r "Microsoft.Azure.WebJobs.Host"
#r "Microsoft.Azure.WebJobs.Extensions"
#r "System.Web.Http"
#r "System.Net.Http.Formatting"
